@startuml database_er
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

' 平台管理员
entity "Admin" as a1 {
    * id : number <<generated>>
    ---
    * username : varchar
    * password : varchar(32) <<MD5>>
}

' 团队管理员
entity "Group_Admin" as a2  {
        * id : number <<generated>>
        ---
        * group_id : number
        * username : varchar
        * password : varchar(32) <<MD5>>
}

' 团队
entity "Group" as g {
    * id : number <<generated>>
    ---
    * name : varchar
    * organizaion : varchar
    * code : varchar
}

' 志愿者
entity "Volunteer" as v {
    * id : number <<generated>>
    ---
    * group_id : number
    * name : varchar
    * id_number : varchar
    * gender : bool
    * employment : varchar
    * avatar : varchar
    * intention : varchar
    * experience : text
    * tel : text
    job_id : number
}

' 岗位
entity "Job" as j {
    * id : number <<generated>>
    ---
    * group_id : number
    * name : varchar
    * content : varchar
    * location : varchar
}

g ||..|{ a2
g ||..|{ v
g ||..|{ j
v |o--o{ j
'
@enduml
