name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: make build
    - name: Display all dists
      run: ls dist
  
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.NODE_SERVER_SSH_PRIVATE_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/" 
          REMOTE_HOST: ${{ secrets.NODE_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.NODE_SERVER_USER}}
          TARGET: ${{ secrets.NODE_SERVER_TARGET}}
          EXCLUDE: ""   

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v1

    
